name: miforge-stack

services:
  database:
    image: mariadb
    container_name: database
    restart: unless-stopped
    networks:
      - devnet
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro

  cache:
    image: eqalpha/keydb
    container_name: cache
    restart: unless-stopped
    env_file: .env
    networks:
      - devnet
    command: >
      keydb-server
      --appendonly yes
      --save 900 1 --save 300 10 --save 60 10000
      --protected-mode no
      --requirepass ${KEYDB_PASSWORD}
      --databases 16
      --dbfilename dump.rdb
      --dir /data
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data

networks:
  devnet:
    external: true
    name: devnet

volumes:
  db_data:
  keydb_data:
